name: hasnain_ui_button
description: A customizable button widget package for Flutter applications
version: 0.0.2
homepage: https://github.com/shadid06/hasnain_ui_button

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
