name: hasnain_ui_button
description: A customizable button widget package for Flutter applications
version: 0.0.5
homepage: https://github.com/shadid06/hasnain_ui_button
screenshots:
  - description: A customizable button widget package for Flutter applications
    path: example/hasnain_ui_button_example.png

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
